### ISSUE TITLE
The version is not added correctly

### ISSUE THREAD

**Issue by umbynos** [arduino/rp2040tools#21]
Apparently, the `${GITHUB_REF##*/}` variable is not expanded correctly in the release CI. This bug has been introduced in #4 
```
./rp2040load -v
rp2040load ${GITHUB_REF##*/} - compiled with go1.16.2
```

**Comment by per1234** [comment]
I think it is caused by the environment variable having been wrapped in single quotes:

https://github.com/arduino/rp2040tools/blob/8f73b2f1835f9abdd4f5dc44cd375f6754f14e7f/.github/workflows/release.yml#L166
