### ISSUE TITLE
Add CI workflows to enhance the dev experience

### ISSUE THREAD

**Issue by umbynos** [arduino/rp2040tools#24]
Add some [checks workflows](https://github.com/arduino/tooling-project-assets/tree/main/workflow-templates) to this repo to enhance the developer experience and to catch common problems (like the one from https://github.com/arduino/rp2040tools/pull/23)

**Comment by umbynos** [comment]
We could start integrating [check-go-task](https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-go-task.md) in this repository

**Comment by umbynos** [comment]
These two could be another great addition:
- [sync-labels](https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/sync-labels.md)
- [check-markdown-task](https://github.com/arduino/arduino-cli/blob/master/.github/workflows/check-markdown-task.md)

**Comment by umbynos** [comment]
> We could start integrating [check-go-task](https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-go-task.md) in this repository.

Done by @MatteoPologruto in #25

**Comment by MatteoPologruto** [comment]
Added the following checks:
- [Check-go-task](https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-go-task.md) (PR #[25](https://github.com/arduino/rp2040tools/pull/25))
- [Check-markdown-task](https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-markdown-task.md) (PR #[27](https://github.com/arduino/rp2040tools/pull/27))
- [Check-prettier-formatting-task](https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-prettier-formatting-task.md) (PR #[28](https://github.com/arduino/rp2040tools/pull/28))
- [Check-taskfiles](https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-taskfiles.md) (PR #[29](https://github.com/arduino/rp2040tools/pull/29))

Minor additions:
- [main.go](https://github.com/arduino/rp2040tools/blob/master/main.go) style fix (PR #[26](https://github.com/arduino/rp2040tools/pull/26))
- added sync-labels badge to [README.md](https://github.com/arduino/rp2040tools/blob/master/README.md) (PR #[30](https://github.com/arduino/rp2040tools/pull/30))
