### ISSUE TITLE
Can't upload sketch on linux.

### ISSUE THREAD

**Issue by qwec01** [arduino/rp2040tools#9]
I use raspberry pi pico, I can upload sketch on windows, but can't upload on linux. When I hit "upload" button, the compile is success, the pico is in BOOTSEL state, but upload fails. Plese help. Here's some log.(uploading blink)

Sketch uses 13932 bytes (0%) of program storage space. Maximum is 16777216 bytes.
Global variables use 42780 bytes (15%) of dynamic memory, leaving 227556 bytes for local variables. Maximum is 270336 bytes.
/home/x210/.arduino15/packages/arduino/tools/rp2040tools/1.0.2/rp2040load -v -D /tmp/arduino_build_25821/Blink.ino.elf 
rp2040load 1.0.1 - compiled with go1.15.8
.....................
An error occurred while uploading the sketch

**Comment by facchinm** [comment]
Hi @qwec01 ,
the uploader uses the raw USB interface to flash the pico. You may need to add an udev rule to be able to use it without root permissions.
Running this script https://github.com/arduino/ArduinoCore-mbed/blob/master/post_install.sh should do the trick

**Comment by qwec01** [comment]
> 

Thank you very much, it worked!

**Comment by tttapa** [comment]
I think it would be helpful to add this to the installation instructions and the [arduino/ArduinoCore-mbed](https://github.com/arduino/ArduinoCore-mbed) README.
Perhaps the error message can be improved as well (e.g. suggesting that the udev rules might not be installed correctly and providing a link to the instructions when this error occurs).

**Comment by per1234** [comment]
Hi @tttapa. Thanks for your valuable suggestions. I think it will be too difficult to track them in this closed issue, so I would request you to open two dedicated issues:

- One in this repository requesting meaningful feedback from `rp2040load`
- One in the appropriate repository requesting documentation of the Linux post install script

As for the latter, my opinion is that the `arduino/ArduinoCore-mbed` readme is not an effective place to document this information. The users who need it most will never see that readme. Better would be one of the following:

- https://github.com/arduino/docs-content
  - This would likely be the appropriate location to document it: https://github.com/arduino/docs-content/blob/main/content/hardware/03.nano/boards/nano-rp2040-connect/tutorials/rp2040-01-technical-reference/rp2040-01-technical-reference.md
- https://github.com/arduino/help-center-content
  - I think the help center is the most appropriate place for documenting procedures that are less commonly required. If this is something every Linux user must do, then docs.arduino.cc would be the better place (perhaps supplemented by a Help Center article keyed off the symptoms of skipping that procedure, which links to the information on docs.arduino.cc)
